services:
  tseho.doctrine_assigned_identity.listener:
    class: Tseho\DoctrineAssignedIdentity\EventListener\AssignedIdentityListener
    public: false
    tags:
      - { name: doctrine.event_listener, event: prePersist }
